from common import *
from ontology_populator.implementations.core import *
from ontology_populator.implementations.knime.knime_implementation import KnimeImplementation, KnimeParameter, KnimeDynamicBundle, KnimeJSViewsFeature

piechart_visualizer_implementation = KnimeImplementation(
    name = "Pie_Donut Chart",
    algorithm = cb.PieChart,
    parameters = [

        KnimeParameter("Generate Image Model", XSD.boolean, False, 'generateImagemodel', path="model"),
        KnimeParameter("GIMI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/generateImagemodel_Internals"),
        KnimeParameter("GIMI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/generateImagemodel_Internals"),
        KnimeParameter("Pie Chart Category", XSD.string, "$$PIE_CATEGORICAL$$", 'cat', path="model"),
        KnimeParameter("CI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/cat_Internals"),
        KnimeParameter("CI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/cat_Internals"),
        KnimeParameter("Pie Aggregation", XSD.string, "Sum", 'aggr', path="model"), 
        KnimeParameter("AGGI SettingsModelID", XSD.string, "SMID_string", 'SettingsModelID',
                       path="model/aggr_Internals"),
        KnimeParameter("AGGI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/aggr_Internals"),
        KnimeParameter("Report On Missing Values", XSD.boolean, True, 'reportOnMissingValues', path="model"),
        KnimeParameter("ROMVI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/reportOnMissingValues_Internals"),
        KnimeParameter("ROMVI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/reportOnMissingValues_Internals"),
        KnimeParameter("Include Missing Values Category", XSD.boolean, True, 'includeMissValCat', path="model"),
        KnimeParameter("IMVCI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/includeMissValCat_Internals"),
        KnimeParameter("IMVCI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/includeMissValCat_Internals"),
        KnimeParameter("frequency", XSD.string, "$$PIE_NUMERICAL$$", 'freq', path="model"),
        KnimeParameter("FrI SettingsModelID", XSD.string, "SMID_string", 'SettingsModelID',
                       path="model/freq_Internals"),
        KnimeParameter("FrI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/freq_Internals"),
        KnimeParameter("Process In Memory", XSD.boolean, True, 'processInMemory', path="model"),
        KnimeParameter("PIMI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/processInMemory_Internals"),
        KnimeParameter("PIMI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/processInMemory_Internals"),
        KnimeParameter("title", XSD.string, "Pie Chart", 'title', path="model"),
        KnimeParameter("TI SettingsModelID", XSD.string, "SMID_string", 'SettingsModelID',
                       path="model/title_Internals"),
        KnimeParameter("TI EnabledStatus", XSD.boolean, True, "EnabledStatus",
                      path="model/title_Internals"),
        KnimeParameter("subtitle", XSD.string, "", 'subtitle', path="model"),
        KnimeParameter("SUBI SettingsModelID", XSD.string, "SMID_string", 'SettingsModelID',
                       path="model/subtitle_Internals"),
        KnimeParameter("SUBI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/subtitle_Internals"),
        KnimeParameter("togglePie", XSD.boolean, False, 'togglePie', path="model"),
        KnimeParameter("TPI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/togglePie_Internals"),
        KnimeParameter("TPI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/togglePie_Internals"),
        KnimeParameter("holeSize", XSD.double, 0.35, 'holeSize', path="model"),
        KnimeParameter("HSI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/holeSize_Internals"),
        KnimeParameter("HSI EnabledStatus", XSD.boolean, False, 'EnabledStatus',
                       path="model/holeSize_Internals"),
        KnimeParameter("insideTitle", XSD.string, "", 'insideTitle', path="model"),
        KnimeParameter("INI SettingsModelID", XSD.string, "SMID_string", 'SettingsModelID',
                       path="model/insideTitle_Internals"),
        KnimeParameter("INI EnabledStatus", XSD.boolean, False, 'EnabledStatus',
                       path="model/insideTitle_Internals"),
        KnimeParameter("customColors", XSD.boolean, False, 'customColors', path="model"),
        KnimeParameter("CCI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/customColors_Internals"),
        KnimeParameter("CCI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/customColors_Internals"),
        KnimeParameter("legend", XSD.boolean, True, 'legend', path="model"),
        KnimeParameter("LEI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/legend_Internals"),
        KnimeParameter("LEI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/legend_Internals"),
        KnimeParameter("showLabels", XSD.boolean, True, 'showLabels', path="model"),
        KnimeParameter("SLI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/showLabels_Internals"),
        KnimeParameter("SLI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/showLabels_Internals"),
        KnimeParameter("labelType", XSD.string, "Value", 'labelType', path="model"),
        KnimeParameter("LTI SettingsModelID", XSD.string, "SMID_string", 'SettingsModelID',
                       path="model/labelType_Internals"),
        KnimeParameter("LTI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/labelType_Internals"),
        KnimeParameter("labelThreshold", XSD.double, 0.05, 'labelThreshold', path="model"),
        KnimeParameter("LTHI SettingsModelID", XSD.string, "SMID_double", 'SettingsModelID',
                       path="model/labelThreshold_Internals"),
        KnimeParameter("LTHI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/labelThreshold_Internals"),
        KnimeParameter("Display Full Screen Button", XSD.boolean, True, 'displayFullscreenButton', path="model"),
        KnimeParameter("DFBI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/displayFullscreenButton_Internals"),
        KnimeParameter("DFBI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/displayFullscreenButton_Internals"),
        KnimeParameter("svg_width", XSD.integer, 600, 'width', path="model/svg"), 
        KnimeParameter("svg_height", XSD.integer, 400, 'height', path="model/svg"), 
        KnimeParameter("svg_fullscreen", XSD.boolean, True, 'fullscreen', path="model/svg"), 
        KnimeParameter("svg_showFullscreen", XSD.boolean, True, 'showFullscreen', path="model/svg"), 
        KnimeParameter("SVGI SettingsModelID", XSD.string, "SMID_svg", 'SettingsModelID',
                       path="model/svg_Internals"),
        KnimeParameter("SVGI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/svg_Internals"),
        KnimeParameter("Show Warnings", XSD.boolean, True, 'showWarnings', path="model"),
        KnimeParameter("SWI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/showWarnings_Internals"),
        KnimeParameter("SWI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/showWarnings_Internals"),
        KnimeParameter("enableViewControls", XSD.boolean, True, 'enableViewControls', path="model"),
        KnimeParameter("EVCI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableViewControls_Internals"),
        KnimeParameter("EVCI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableViewControls_Internals"),
        KnimeParameter("enableTitleEdit", XSD.boolean, True, 'enableTitleEdit', path="model"),
        KnimeParameter("ETEI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableTitleEdit_Internals"),
        KnimeParameter("ETEI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableTitleEdit_Internals"),
        KnimeParameter("enableSubtitleEdit", XSD.boolean, True, 'enableSubtitleEdit', path="model"),
        KnimeParameter("ESEI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableSubtitleEdit_Internals"),
        KnimeParameter("ESEI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableSubtitleEdit_Internals"),
        KnimeParameter("enableDonutToggle", XSD.boolean, True, 'enableDonutToggle', path="model"),
        KnimeParameter("EDTI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableDonutToggle_Internals"),
        KnimeParameter("EDTI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableDonutToggle_Internals"),
        KnimeParameter("enableHoleEdit", XSD.boolean, True, 'enableHoleEdit', path="model"),
        KnimeParameter("EHEI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableHoleEdit_Internals"),
        KnimeParameter("EHEI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableHoleEdit_Internals"),
        KnimeParameter("enableInsideTitleEdit", XSD.boolean, True, 'enableInsideTitleEdit', path="model"),
        KnimeParameter("EIEI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableInsideTitleEdit_Internals"),
        KnimeParameter("EIEI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableInsideTitleEdit_Internals"),
        KnimeParameter("enableColumnChooser", XSD.boolean, True, 'enableColumnChooser', path="model"),
        KnimeParameter("ECCI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableColumnChooser_Internals"),
        KnimeParameter("ECCI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableColumnChooser_Internals"),
        KnimeParameter("enableLabelEdit", XSD.boolean, True, 'enableLabelEdit', path="model"),
        KnimeParameter("ELEI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableLabelEdit_Internals"),
        KnimeParameter("ELEI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableLabelEdit_Internals"),
        KnimeParameter("enableSwitchMissValCat", XSD.boolean, True, 'enableSwitchMissValCat', path="model"),
        KnimeParameter("ESMI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableSwitchMissValCat_Internals"),
        KnimeParameter("ESMI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableSwitchMissValCat_Internals"),
        KnimeParameter("enableSelection", XSD.boolean, True, 'enableSelection', path="model"),
        KnimeParameter("ESI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/enableSelection_Internals"),
        KnimeParameter("ESI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/enableSelection_Internals"),
        KnimeParameter("subscribeToSelection", XSD.boolean, True, 'subscribeToSelection', path="model"),
        KnimeParameter("STSI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/subscribeToSelection_Internals"),
        KnimeParameter("STSI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/subscribeToSelection_Internals"),
        KnimeParameter("publishSelection", XSD.boolean, True, 'publishSelection', path="model"),
        KnimeParameter("PSI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/publishSelection_Internals"),
        KnimeParameter("PSI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/publishSelection_Internals"),
        KnimeParameter("displayClearSelectionButton", XSD.boolean, True, 'displayClearSelectionButton', path="model"),
        KnimeParameter("DCSI SettingsModelID", XSD.string, "SMID_boolean", 'SettingsModelID',
                       path="model/displayClearSelectionButton_Internals"),
        KnimeParameter("DCSI EnabledStatus", XSD.boolean, True, 'EnabledStatus',
                       path="model/displayClearSelectionButton_Internals"),
        KnimeParameter("hideInWizard", XSD.boolean, False, 'hideInWizard', path="model"),
        KnimeParameter("maxRows", XSD.integer, 2500, 'maxRows', path="model"),
        KnimeParameter("generateImage", XSD.boolean, True, 'generateImage', path="model"),
        KnimeParameter("customCSS", XSD.string, "", 'customCSS', path="model"),
        KnimeParameter("Node Dir", XSD.string, "org.knime.dynamic.js.base:nodes/:donutChart", 'nodeDir',
                       path="factory_settings"),

    ],
    input = [
        cb.TabularDataset
    ],
    output = [
        cb.PieChartVisualizationShape
    ],
    implementation_type = tb.VisualizerImplementation,
    knime_node_factory = 'org.knime.dynamic.js.v30.DynamicJSNodeFactory',
    knime_bundle = KnimeDynamicBundle,
    knime_feature = KnimeJSViewsFeature,
)


piechart_sum_visualizer_component = Component(
    name = "Pie Chart Sum Visualizer",
    implementation = piechart_visualizer_implementation,
    exposed_parameters = [
        next((param for param in piechart_visualizer_implementation.parameters.keys() if param.knime_key == 'cat'), None), ### category column
        next((param for param in piechart_visualizer_implementation.parameters.keys() if param.knime_key == 'freq'), None) ### frequency column (optional)
    ],
    overriden_parameters = [
        ParameterSpecification(next((param for param in piechart_visualizer_implementation.parameters.keys() if param.knime_key == 'aggr'), None), "Sum")
    ],
    transformations = []
)

piechart_count_visualizer_component = Component(
    name = "Pie Chart Count Visualizer",
    implementation = piechart_visualizer_implementation,
    exposed_parameters = [
        next((param for param in piechart_visualizer_implementation.parameters.keys() if param.knime_key == 'cat'), None),
        next((param for param in piechart_visualizer_implementation.parameters.keys() if param.knime_key == 'freq'), None)
    ],
    overriden_parameters = [
        ParameterSpecification(next((param for param in piechart_visualizer_implementation.parameters.keys() if param.knime_key == 'aggr'), None), "Occurence Count")
    ],
    transformations = []
)

piechart_avg_visualizer_component = Component(
    name = "Pie Chart Average Visualizer",
    implementation = piechart_visualizer_implementation,
    exposed_parameters = [
        next((param for param in piechart_visualizer_implementation.parameters.keys() if param.knime_key == 'cat'), None),
        next((param for param in piechart_visualizer_implementation.parameters.keys() if param.knime_key == 'freq'), None)
    ],
    overriden_parameters = [
        ParameterSpecification(next((param for param in piechart_visualizer_implementation.parameters.keys() if param.knime_key == 'aggr'), None), "Average")
    ],
    transformations = []
)